Update patch set 1
Patch Set 1: Code-Review-1

Am I missing something?

packages/apps/Mms/src/com/android/mms/ui/SlideListItemView.java:270: cannot find symbol
symbol  : class MediaMetadataRetriever
location: class com.android.mms.ui.SlideListItemView
        MediaMetadataRetriever mediaMetadataRetriever = new MediaMetadataRetriever();

Patch-set: 1