Update patch set 1
Patch Set 1:

When this bug happened the following was logged in logcat:
[ 10-04 19:24:35.575  2842: 3023 E/CursorWindow ]
Failed to read row 1652, column 1 from a CursorWindow which has 1652 rows, 26 columns.

[ 10-04 19:24:35.575  2842: 3023 E/DatabaseUtils ]
Writing exception to parcel
java.lang.IllegalStateException: Couldn't read row 1652, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:507)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
	at android.database.CursorToBulkCursorAdaptor.getWindow(CursorToBulkCursorAdaptor.java:164)
	at android.database.BulkCursorNative.onTransact(BulkCursorNative.java:64)
	at android.os.Binder.execTransact(Binder.java:404)
	at dalvik.system.NativeStart.run(Native Method)


[ 10-04 19:24:35.575 15840:15840 D/AndroidRuntime ]
Shutting down VM


[ 10-04 19:24:35.575 15840:15840 W/dalvikvm ]
threadid=1: thread exiting with uncaught exception (group=0x41915ce0)

[ 10-04 19:24:35.575 15840:15840 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.android.mms, PID: 15840
java.lang.IllegalStateException: Couldn't read row 1652, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.os.Parcel.readException(Parcel.java:1473)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
	at android.database.BulkCursorProxy.getWindow(BulkCursorNative.java:164)
	at android.database.BulkCursorToCursorAdaptor.onMove(BulkCursorToCursorAdaptor.java:83)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:214)
	at android.database.AbstractCursor.moveToLast(AbstractCursor.java:241)
	at android.database.CursorWrapper.moveToLast(CursorWrapper.java:154)
	at com.android.mms.ui.ComposeMessageActivity$BackgroundQueryHandler.onQueryComplete(ComposeMessageActivity.java:4509)
	at android.content.AsyncQueryHandler.handleMessage(AsyncQueryHandler.java:344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

Patch-set: 1